/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package planner.etapa1.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import planner.etapa1.Lembretes;
import planner.etapa1.LembretesDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import nova.model.filmeDAO;

/**
 *
 * @author rebec
 */
public class TelaMeusLembretes extends javax.swing.JFrame {

    /**
     * Creates new form TelaMeusLembretes
     */
    public TelaMeusLembretes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cenaflix1 = new nova.view.Cenaflix();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        voltarMenu = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        IrParaLembretes = new javax.swing.JButton();
        atualizarTabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel1.setText("Meus Lembretes");

        tabela1.setModel(montarTabela());
        jScrollPane1.setViewportView(tabela1);

        voltarMenu.setBackground(new java.awt.Color(0, 102, 0));
        voltarMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltarMenu.setForeground(new java.awt.Color(255, 255, 255));
        voltarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/angulo-esquerdo.png"))); // NOI18N
        voltarMenu.setText("Voltar");
        voltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarMenuActionPerformed(evt);
            }
        });

        excluir.setBackground(new java.awt.Color(0, 102, 0));
        excluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        excluir.setForeground(new java.awt.Color(255, 255, 255));
        excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/lixeira-xmark.png"))); // NOI18N
        excluir.setText(" Excluir Lembretes");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        IrParaLembretes.setBackground(new java.awt.Color(0, 102, 0));
        IrParaLembretes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IrParaLembretes.setForeground(new java.awt.Color(255, 255, 255));
        IrParaLembretes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/procurar (1).png"))); // NOI18N
        IrParaLembretes.setText("Novo Lembrete");
        IrParaLembretes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrParaLembretesActionPerformed(evt);
            }
        });

        atualizarTabela.setBackground(new java.awt.Color(0, 102, 0));
        atualizarTabela.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        atualizarTabela.setForeground(new java.awt.Color(255, 255, 255));
        atualizarTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/atualizar.png"))); // NOI18N
        atualizarTabela.setText("Atualizar Tabela");
        atualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IrParaLembretes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(voltarMenu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(atualizarTabela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(excluir)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atualizarTabela)
                            .addComponent(excluir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltarMenu)
                    .addComponent(IrParaLembretes, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarMenuActionPerformed
        MenuInicial mi = new MenuInicial();
        mi.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarMenuActionPerformed

    private void IrParaLembretesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrParaLembretesActionPerformed
        TelaLembretes tl = new TelaLembretes();
        tl.setVisible(true);
        dispose();
    }//GEN-LAST:event_IrParaLembretesActionPerformed

    private void atualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarTabelaActionPerformed
        tabela1.setModel(montarTabela());
    }//GEN-LAST:event_atualizarTabelaActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        int id = getPosicao();
        int resposta = JOptionPane.showConfirmDialog(null, "Ao clicar em 'Sim' você confirma a exclusão permamente do item.");

        if (resposta == 0) {
            LembretesDAO.excluir(id);
        }

        tabela1.setModel(montarTabela());
    }//GEN-LAST:event_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMeusLembretes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMeusLembretes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMeusLembretes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMeusLembretes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMeusLembretes().setVisible(true);
            }
        });
    }

    private DefaultTableModel montarTabela() {

        String[] colunas = {"ID", "Titulo", "Descrição", "Data"};
        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);

        List<Lembretes> lista = LembretesDAO.listar();

        for (int i = 0; i < lista.size(); i++) {
            Lembretes l = lista.get(i);

            String[] linha = {
                Integer.toString(l.getId()),
                l.getTitulo(),
                l.getDescricao(),
                l.converterParaJava(l.getData())

            };

            tabela.addRow(linha);
        }

        return tabela;

    }

    private int getPosicao() {
        int posicao = tabela1.getSelectedRow();

        if (posicao <= -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
        return Integer.parseInt((String) tabela1.getValueAt(posicao, 0));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IrParaLembretes;
    private javax.swing.JButton atualizarTabela;
    private nova.view.Cenaflix cenaflix1;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela1;
    private javax.swing.JButton voltarMenu;
    // End of variables declaration//GEN-END:variables
}
